---
- name: Remove nginx container
  community.docker.docker_container:
    name: nginx
    state: absent
  ignore_errors: true

- name: Pull dashboard image
  community.docker.docker_image:
    name: "{{ app_dashboard_image }}"
    source: pull
    force_source: true

- name: Run dashboard container
  community.docker.docker_container:
    name: cloudops-dashboard
    image: "{{ app_dashboard_image }}"
    state: started
    restart_policy: always
    recreate: true
    published_ports:
      - "80:5000"
    env:
      APP_VERSION: "{{ app_version }}"
      BUILD_NUMBER: "{{ app_build_number }}"